export const fontCatalog = [
  { name: 'Arial', family: 'Arial, sans-serif' },
  { name: 'DM Sans', family: 'DM Sans, sans-serif' },
  { name: 'Inter', family: 'Inter, sans-serif' },
  { name: 'Manrope', family: 'Manrope, sans-serif' },
  { name: 'Montserrat', family: 'Montserrat, sans-serif' },
  { name: 'Poppins', family: 'Poppins, sans-serif' },
  { name: 'Space Grotesk', family: 'Space Grotesk, sans-serif' },
  { name: 'Bebas Neue', family: 'Bebas Neue, sans-serif' },
  { name: 'Oswald', family: 'Oswald, sans-serif' },
  { name: 'Playfair Display', family: 'Playfair Display, serif' },
  { name: 'Lora', family: 'Lora, serif' },
  { name: 'Libre Baskerville', family: 'Libre Baskerville, serif' },
  { name: 'Merriweather', family: 'Merriweather, serif' },
  { name: 'Caveat', family: 'Caveat, cursive' },
  { name: 'Pacifico', family: 'Pacifico, cursive' },
  { name: 'Courier New', family: 'Courier New, monospace' },
  { name: 'Georgia', family: 'Georgia, serif' },
  { name: 'Impact', family: 'Impact, sans-serif' },
  { name: 'Trebuchet MS', family: 'Trebuchet MS, sans-serif' },
  { name: 'Verdana', family: 'Verdana, sans-serif' },
] as const;
